[package]

name = "client"
version = "0.0.1"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]

[dependencies]
common = { path = "../common" }
time = "0.1"
xmath = "0.1"
glium = { version = "0.7", default-features = false, features = ["glutin"] }
