[package]

name = "client"
version = "0.0.1"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]

[dependencies]
common = { path = "../common" }
glium = { version = "*", default-features = false }
glutin = "*"
obj-rs = { version = "*", features = ["glium-support"] }
