[package]

name = "client"
version = "0.0.1"
authors = ["Hyeon Kim <simnalamburt@gmail.com>"]

[dependencies]
common = { path = "../common" }
time = "*"
xmath = "0.1"
glium = { version = "*", default-features = false, features = ["glutin"] }
