language: rust
install:
  - sudo apt-get install libXxf86vm-dev
env:
  - SUBDIR=common
  - SUBDIR=server
  - SUBDIR=client
script: cd $SUBDIR && cargo build && cargo test
notifications:
  irc:
    nick: glium-practice
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
